### ISSUE TITLE
Troubles uploading photos

### ISSUE THREAD

**Issue by juliannamcm** [TraceyLauriault/COMS2200A#18] opened 2017-10-10 22:10 UTC
Hi I am having troubles being able to continue on openstreetmap of uploading a photo. There is an error with my account which will not allow me to continue. 
Here is a message that just popped up when I tried to reload.
![20171010_180619](https://user-images.githubusercontent.com/32115025/31413193-29a6b28c-ade6-11e7-8606-cb0d4a599874.jpg)

**Comment by DenisCarriere** [comment] 2017-10-10 22:12
Duplicate of https://github.com/TraceyLauriault/COMS2200A/issues/15

**Closed as completed by DenisCarriere** 2017-10-10 22:12 UTC
